-- MySQL Script generated by MySQL Workbench
-- lun 26 abr 2021 19:30:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema persefone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema persefone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `persefone` ;
USE `persefone` ;

-- -----------------------------------------------------
-- Table `persefone`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persefone`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(13) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persefone`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persefone`.`tarjeta` (
  `idtarjeta` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(50) NOT NULL,
  `banco` VARCHAR(50) NOT NULL,
  `vencimiento` DATE NOT NULL,
  `cvv` VARCHAR(4) NOT NULL,
  `idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idtarjeta`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `fk_clienteID_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_clienteID`
    FOREIGN KEY (`idcliente`)
    REFERENCES `persefone`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persefone`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persefone`.`compra` (
  `idcompra` INT(11) NOT NULL AUTO_INCREMENT,
  `hora` DATETIME NOT NULL,
  `total` DECIMAL(7,2) NOT NULL,
  `idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_clienteID_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_clienteID_1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `persefone`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persefone`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persefone`.`producto` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `imagen` VARCHAR(200) NOT NULL,
  `precio` DECIMAL(7,2) NOT NULL,
  `inventario` INT NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persefone`.`detalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persefone`.`detalleCompra` (
  `iddetalleCompra` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `subtotal` DECIMAL(7,2) NOT NULL,
  `idcompra` INT(11) NOT NULL,
  `idproducto` INT(11) NOT NULL,
  PRIMARY KEY (`iddetalleCompra`),
  INDEX `fk_idCompra_idx` (`idcompra` ASC) VISIBLE,
  INDEX `fk_idProducto_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_idCompra`
    FOREIGN KEY (`idcompra`)
    REFERENCES `persefone`.`compra` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProducto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `persefone`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persefone`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persefone`.`proveedor` (
  `idproveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(13) NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `persefone`.`mercancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `persefone`.`mercancia` (
  `idmercancia` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaCompra` DATETIME NOT NULL,
  `cantidad` INT NOT NULL,
  `idproducto` INT(11) NOT NULL,
  `idproveedor` INT(11) NOT NULL,
  PRIMARY KEY (`idmercancia`),
  INDEX `fk_idProducto_idx` (`idproducto` ASC) VISIBLE,
  INDEX `fk_idProveedor_idx` (`idproveedor` ASC) VISIBLE,
  CONSTRAINT `fk_idProducto_1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `persefone`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProveedor`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `persefone`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
